package com.leetylarry.theo;

public enum TokenType {
    // Keywords
    AND, OR, IF, ELSE, TRUE, FALSE, CLASS, THIS, SUPER, RETURN,
    FOR, WHILE, NIL, PRINT,

    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMI_COLON, SLASH, STAR,
    EXCLAMATION, EXCLAMATION_EQUAL, EQUAL, DOUBLE_EQUAL,
    GREATER_THAN, GREATER_THAN_EQUAL, LESS_THAN, LESS_THAN_EQUAL,

    NUMBER, IDENTIFIER, EOF
}
